=== iofro/gestor-de-inventario/svfe-json-schemas/anulacion-schema-v2.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Invalidacion de Documento Tributario Electronico",
	"type": "object",
	"properties": {
		"identificacion": {
			"description": "Informacion de identificacion de Invalidacion",
			"type": "object",
			"properties": {
				"version": {
					"type": "integer",
					"description": "Version del esquema",
					"const": 2
				},
				"ambiente": {
					"type": "string",
					"description": "Ambiente de destino: 00 - Pruebas, 01 - Produccion",
					"enum": ["00", "01"]
				},
				"codigoGeneracion": {
					"type": "string",
					"description": "Codigo Generacion",
					"maxLength": 36,
					"minLength": 36,
					"pattern": "^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$"
				},
				"fecAnula": {
					"type": "string",
					"description": "Fecha de invalidacion (formato yyyy-mm-dd)",
					"format": "date"
				},
				"horAnula": {
					"type": "string",
					"description": "Hora de invalidacion",
					"pattern": "^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]?$"
				}
			},
			"additionalProperties": false,
			"required": ["version", "ambiente", "codigoGeneracion", "fecAnula", "horAnula"]
		},
		"emisor": {
			"description": "Datos del emisor",
			"type": "object",
			"properties": {
				"nit": {
					"description": "NIT, sin guiones",
					"type": "string",
					"pattern": "^([0-9]{14}|[0-9]{9})$"
				},
				"nombre": {
					"type": "string",
					"description": "Nombre/Denominacion/Razon social",
					"maxLength": 250,
					"minLength": 3
				},
				"tipoEstablecimiento": {
					"type": "string",
					"description": "Tipo establecimiento donde se emite documento",
					"enum": ["01", "02", "04", "07", "20"]
				},
				"nomEstablecimiento": {
					"description": "Nombre de establecimiento",
					"type": ["string", "null"],
					"maxLength": 150,
					"minLength": 3
				},
				"codEstableMH": {
					"description": "Codigo, Numero o Identificador de establecimiento por MH",
					"type": [
						"string",
						"null"
					],
					"maxLength": 4,
					"minLength": 4
				},
				"codEstable": {
					"description": "Codigo, Numero o Identificador de establecimiento por Contribuyente",
					"type": [
						"string",
						"null"
					],
					"minLength": 1,
					"maxLength": 10
				},
				"codPuntoVentaMH": {
					"description": "Codigo, Numero o Identificador de punto de venta por MH",
					"type": [
						"string",
						"null"
					],
					"maxLength": 4,
					"minLength": 4
				},
				"codPuntoVenta": {
					"description": "Codigo, Numero o Identificador de punto de venta por Contribuyente",
					"type": [
						"string",
						"null"
					],
					"maxLength": 15,
					"minLength": 1
				},
				"telefono": {
					"type": ["string", "null"],
					"description": "Numero de telefono del emisor",
					"minLength": 8,
					"maxLength": 26,
					"pattern": "^[0-9+;]{8,26}$"
				},
				"correo": {
					"type": "string",
					"description": "Correo electronico del emisor",
					"format": "email",
					"maxLength": 100,
					"minLength": 3
				}
			},
			"additionalProperties": false,
			"required": ["nit", "nombre", "tipoEstablecimiento", "telefono", "correo", "codEstable", "codPuntoVenta", "nomEstablecimiento"]
		},
		"documento": {
			"description": "Datos del documento a Invalidar",
			"type": "object",
			"properties": {
				"tipoDte": {
					"type": "string",
					"description": "Tipo de documento",
					"pattern": "^0[0-9]|1[0-5]$",
					"enum": ["01",
						"03",
						"04",
						"05",
						"06",
						"07",
						"08",
						"09",
						"10",
						"11",
						"14",
						"15"
					]
				},
				"codigoGeneracion": {
					"type": "string",
					"description": "Codigo Generacion",
					"maxLength": 36,
					"minLength": 36,
					"pattern": "^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$"
				},
				"selloRecibido": {
					"type": "string",
					"description": "Sello de recepcion",
					"maxLength": 40,
					"minLength": 40,
					"pattern": "^[A-Z0-9]{40}$"
				},
				"numeroControl": {
					"type": "string",
					"description": "Numero control",
                                        "maxLength": 34,
                                        "minLength": 34,
                                        "pattern": "^DTE-0[0-9]|1[0-2]-[A-Z0-9]{8}-[0-9]{18}$"
				},
				"fecEmi": {
					"type": "string",
					"description": "Fecha de emision (formato yyyy-mm-dd)",
					"format": "date"
				},
				"montoIva": {
					"type": ["number", "null"],
					"description": "Monto IVA",
					"minimum": 0,
					"exclusiveMaximum": 100000000000,
					"multipleOf": 0.01
				},
				"codigoGeneracionR": {
					"type": ["string", "null"],
					"description": "Codigo Generacion que reemplaza",
					"maxLength": 36,
					"minLength": 36,
					"pattern": "^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$"
				},
				"tipoDocumento": {
					"type": "string",
					"description": "Tipo documento de identificación CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO",
					"enum": ["36", "13", "02", "03", "37"]
				},
				"numDocumento": {
					"type": "string",
					"description": "Número de documento de Identificación ",
					"minLength": 3,
					"maxLength": 20
				},
				"nombre": {
					"type": "string",
					"description": "Nombre/Denominacion/Razon social",
					"maxLength": 200,
					"minLength": 5
				},
				"telefono": {
					"type": ["string", "null"],
					"description": "Numero de telefono del receptor",
					"minLength": 8,
					"maxLength": 50,
					"pattern": "^[0-9+;]{8,50}$"
				},
				"correo": {
					"type": "string",
					"description": "Correo electronico del receptor",
					"format": "email",
					"maxLength": 100
				}
			},
			"additionalProperties": false,
			"required": ["tipoDte", "codigoGeneracion", "selloRecibido", "numeroControl", "fecEmi", "montoIva", "codigoGeneracionR", "tipoDocumento", "numDocumento", "nombre"]
		},
		"motivo": {
			"description": "Datos del motivo de Invalidacion",
			"type": "object",
			"properties": {
				"tipoAnulacion": {
					"type": "integer",
					"description": "Tipo de invalidacion",
					"enum": [1, 2, 3]
				},
				"motivoAnulacion": {
					"type": ["string", "null"],
					"description": "Motivo de invalidacion",
					"maxLength": 250,
					"minLength": 5
				},
				"nombreResponsable": {
					"description": "Nombre de la persona responsable de invalidar el DTE",
					"type": "string",
					"maxLength": 100,
					"minLength": 5
				},
				"tipDocResponsable": {
					"type": "string",
					"description": "Tipo documento de identificación CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO",
					"enum": ["36", "13", "02", "03", "37"]
				},
				"numDocResponsable": {
					"type": "string",
					"description": "Número de documento de identificación ",
					"minLength": 3,
					"maxLength": 20
				},
				"nombreSolicita": {
					"description": "Nombre de la persona que solicita invalidar el DTE",
					"type": "string",
					"maxLength": 100,
					"minLength": 5
				},
				"tipDocSolicita": {
					"type": "string",
					"description": "Tipo documento de identificación solicitante CAT-22: 36 - NIT, 13 - DUI, 02 - Carnet de residente, 03 - PASAPORTE, 37 - OTRO",
					"enum": ["36", "13", "02", "03", "37"]
				},
				"numDocSolicita": {
					"type": "string",
					"description": "Número de documento de identificación solicitante.",
					"minLength": 3,
					"maxLength": 20
				}
			},
			"allOf": [{
				"if": {
					"properties": {
						"tipoAnulacion": {
							"const": 3
						}
					}
				},
				"then": {
					"properties": {
						"motivoAnulacion": {
							"type": "string"
						}
					}
				}
			}],
			"additionalProperties": false,
			"required": ["tipoAnulacion", "motivoAnulacion", "nombreResponsable", "tipDocResponsable", "numDocResponsable", "nombreSolicita", "tipDocSolicita", "numDocSolicita"]
		}
	},
	"allOf": [{
		"if": {
			"properties": {
				"motivo": {
					"properties": {
						"tipoAnulacion": {
							"const": 2
						}
					}
				}
			}
		},
		"then": {
			"properties": {
				"documento": {
					"properties": {
						"codigoGeneracionR": {
							"type": "null"
						}
					}
				}
			}
		},
		"else": {
			"properties": {
				"documento": {
					"properties": {
						"codigoGeneracionR": {
							"type": "string"
						}
					}
				}
			}
		}
	}],
	"additionalProperties": false,
	"required": ["identificacion", "emisor", "documento", "motivo"]
}

=== iofro/gestor-de-inventario/dtes/eventos/anulacion/99356A7A-8AE2-4A2E-BFBE-6A0F2A49CFCE/documento.json
{
  "documento": {
    "codigoGeneracion": "C1641927-90E3-4F13-8C65-13E89EF1C105",
    "codigoGeneracionR": null,
    "correo": "cliente1@demo.com",
    "fecEmi": "2025-09-16",
    "montoIva": 1.73,
    "nombre": "ariel",
    "numDocumento": "13240304791012",
    "numeroControl": "DTE-03-S001P001-000000000000195",
    "selloRecibido": "20258C75DA40DA054FE595DB46E815312013PYHZ",
    "telefono": "74154027",
    "tipoDocumento": "36",
    "tipoDte": "03"
  },
  "emisor": {
    "codEstable": "0001",
    "codEstableMH": "0001",
    "codPuntoVenta": "0001",
    "codPuntoVentaMH": "0001",
    "correo": "farmaciasantacatalina7@gmail.com",
    "nit": "09061712791014",
    "nomEstablecimiento": "Farmacia Santa Catalina",
    "nombre": "Karol Yamileth Cruz Escobar",
    "telefono": "22223456",
    "tipoEstablecimiento": "01"
  },
  "identificacion": {
    "ambiente": "00",
    "codigoGeneracion": "99356A7A-8AE2-4A2E-BFBE-6A0F2A49CFCE",
    "fecAnula": "2025-09-16",
    "horAnula": "20:01:00",
    "version": 2
  },
  "motivo": {
    "motivoAnulacion": "koluftn",
    "nombreResponsable": "Karol Yamileth Cruz Escobar",
    "nombreSolicita": "ariel",
    "numDocResponsable": "09061712791014",
    "numDocSolicita": "13240304791012",
    "tipDocResponsable": "36",
    "tipDocSolicita": "36",
    "tipoAnulacion": 2
  }
}

=== iofro/gestor-de-inventario/dtes/eventos/anulacion/2D28E3CD-5E83-4B45-9A34-C00C57843E73/documento.json
{
  "documento": {
    "codigoGeneracion": "0710AB54-4FA3-4C20-B57A-3E29B50E51B7",
    "codigoGeneracionR": null,
    "correo": "cliente1@demo.com",
    "fecEmi": "2025-09-16",
    "montoIva": 1.5,
    "nombre": "ariel",
    "numDocumento": "13240304791012",
    "numeroControl": "DTE-03-S001P001-000000000000194",
    "selloRecibido": "20255D8C8F2156CA4B4D966E27D70B0FB48AEPIE",
    "telefono": "74154027",
    "tipoDocumento": "36",
    "tipoDte": "03"
  },
  "emisor": {
    "codEstable": "0001",
    "codEstableMH": "0001",
    "codPuntoVenta": "0001",
    "codPuntoVentaMH": "0001",
    "correo": "farmaciasantacatalina7@gmail.com",
    "nit": "09061712791014",
    "nomEstablecimiento": "Farmacia Santa Catalina",
    "nombre": "Karol Yamileth Cruz Escobar",
    "telefono": "22223456",
    "tipoEstablecimiento": "01"
  },
  "identificacion": {
    "ambiente": "00",
    "codigoGeneracion": "2D28E3CD-5E83-4B45-9A34-C00C57843E73",
    "fecAnula": "2025-09-16",
    "horAnula": "17:06:21",
    "version": 2
  },
  "motivo": {
    "motivoAnulacion": "devolucion",
    "nombreResponsable": "Karol Yamileth Cruz Escobar",
    "nombreSolicita": "ariel",
    "numDocResponsable": "09061712791014",
    "numDocSolicita": "13240304791012",
    "tipDocResponsable": "36",
    "tipDocSolicita": "36",
    "tipoAnulacion": 2
  }
}
